apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: lukas44/backendv2:1
          ports:
            - containerPort: 5000
          env:
            - name: DB_URL
              value: mongodb://mongodb:27017/comentariosDB