apiVersion: v1
kind: Service
metadata:
  name: web1
spec:
  type: NodePort
  selector:
    app: web1
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: admin
      port: 8080
      targetPort: 8080
      nodePort: 30081
